### ISSUE TITLE
1.19无法正常使用插件Pouvoir

### ISSUE THREAD

**Issue by hanhan2001** [Glom-c/blog#1]
作者您好，是这样的，我尝试在1.19服务器装载你的 Pouvoir 插件，装载之后玩家进入服务器提示 Failed to verify username!，想问下是否是因为我的操作有误，或者是否需要别的修复方式。

**已尝试过的操作**
- 单独开一个服务器并装载前置插件PlaceholderAPI及本体插件Pourvoir
- 翻阅WIKI(可能是我没有找到)
- 正版验证关闭

服务器核心是 Spigot-1.19
以下是装载插件后玩家进入服务器的报错

>[11:08:01] [User Authenticator #2/INFO]: Disconnecting com.mojang.authlib.GameProfile@4611d9e6[id=9b1f680c-f850-3dbc-ace0-c47b84b264e8,name=Xiao_Yingya,properties={},legacy=false] (/192.168.10.2:61183): Failed to verify username!

> [11:08:01] [User Authenticator #2/WARN]: Exception verifying Xiao_Yingya
java.lang.IllegalStateException: AsyncPlayerPreLoginEvent cannot be triggered asynchronously from primary server thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:567) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:375) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3550-Spigot-14a2382-9a8e080]
        at net.minecraft.server.network.LoginListener$1.run(LoginListener.java:267) [spigot-1.19-R0.1-SNAPSHOT.jar:3550-Spigot-14a2382-9a8e080]

> [11:08:01] [Server thread/INFO]: com.mojang.authlib.GameProfile@4611d9e6[id=9b1f680c-f850-3dbc-ace0-c47b84b264e8,name=Xiao_Yingya,properties={},legacy=false] (/192.168.10.2:61183) lost connection: Failed to verify username!

**Comment by Glom-c** [comment]
请使用Paper，Spigot不怎么兼容
